# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableForSolution = QtWidgets.QTableWidget(self.centralwidget)
        self.tableForSolution.setGeometry(QtCore.QRect(10, 100, 881, 201))
        self.tableForSolution.setObjectName("tableForSolution")
        self.tableForSolution.setColumnCount(0)
        self.tableForSolution.setRowCount(0)
        self.buildSolution = QtWidgets.QPushButton(self.centralwidget)
        self.buildSolution.setGeometry(QtCore.QRect(720, 10, 171, 51))
        self.buildSolution.setObjectName("buildSolution")
        self.iterate = QtWidgets.QPushButton(self.centralwidget)
        self.iterate.setGeometry(QtCore.QRect(720, 70, 171, 23))
        self.iterate.setObjectName("iterate")
        self.labelMaxIter = QtWidgets.QLabel(self.centralwidget)
        self.labelMaxIter.setGeometry(QtCore.QRect(10, 10, 271, 16))
        self.labelMaxIter.setObjectName("labelMaxIter")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.label.setObjectName("label")
        self.lineEditForNMAX = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditForNMAX.setGeometry(QtCore.QRect(280, 10, 113, 20))
        self.lineEditForNMAX.setObjectName("lineEditForNMAX")
        self.lineEditForEps = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditForEps.setGeometry(QtCore.QRect(280, 40, 113, 20))
        self.lineEditForEps.setObjectName("lineEditForEps")
        self.labelForIt = QtWidgets.QLabel(self.centralwidget)
        self.labelForIt.setGeometry(QtCore.QRect(10, 70, 171, 16))
        self.labelForIt.setObjectName("labelForIt")
        self.labelForEpsN = QtWidgets.QLabel(self.centralwidget)
        self.labelForEpsN.setGeometry(QtCore.QRect(170, 70, 221, 16))
        self.labelForEpsN.setObjectName("labelForEpsN")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buildSolution.setText(_translate("MainWindow", "Решить"))
        self.iterate.setText(_translate("MainWindow", "Проведи итерацию"))
        self.labelMaxIter.setText(_translate("MainWindow", "Введите максимально допустимое число итераций"))
        self.label.setText(_translate("MainWindow", "Задайте точность"))
        self.labelForIt.setText(_translate("MainWindow", "Проведено итераций: 0"))
        self.labelForEpsN.setText(_translate("MainWindow", "Достигнутая точность: 0.0"))
