# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1175, 320)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableForSolution = QtWidgets.QTableWidget(self.centralwidget)
        self.tableForSolution.setGeometry(QtCore.QRect(10, 70, 791, 201))
        self.tableForSolution.setObjectName("tableForSolution")
        self.tableForSolution.setColumnCount(0)
        self.tableForSolution.setRowCount(0)
        self.buildSolution = QtWidgets.QPushButton(self.centralwidget)
        self.buildSolution.setGeometry(QtCore.QRect(630, 10, 171, 21))
        self.buildSolution.setObjectName("buildSolution")
        self.iterate = QtWidgets.QPushButton(self.centralwidget)
        self.iterate.setGeometry(QtCore.QRect(630, 40, 171, 23))
        self.iterate.setObjectName("iterate")
        self.labelMaxIter = QtWidgets.QLabel(self.centralwidget)
        self.labelMaxIter.setGeometry(QtCore.QRect(10, 10, 271, 16))
        self.labelMaxIter.setObjectName("labelMaxIter")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.label.setObjectName("label")
        self.lineEditForNMAX = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditForNMAX.setGeometry(QtCore.QRect(280, 10, 113, 20))
        self.lineEditForNMAX.setObjectName("lineEditForNMAX")
        self.lineEditForEps = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditForEps.setGeometry(QtCore.QRect(280, 40, 113, 20))
        self.lineEditForEps.setObjectName("lineEditForEps")
        self.labelForIt = QtWidgets.QLabel(self.centralwidget)
        self.labelForIt.setGeometry(QtCore.QRect(810, 30, 341, 16))
        self.labelForIt.setObjectName("labelForIt")
        self.labelForEpsN = QtWidgets.QLabel(self.centralwidget)
        self.labelForEpsN.setGeometry(QtCore.QRect(810, 50, 331, 16))
        self.labelForEpsN.setObjectName("labelForEpsN")
        self.residualEnd = QtWidgets.QLabel(self.centralwidget)
        self.residualEnd.setGeometry(QtCore.QRect(810, 70, 341, 16))
        self.residualEnd.setObjectName("residualEnd")
        self.results = QtWidgets.QLabel(self.centralwidget)
        self.results.setGeometry(QtCore.QRect(810, 10, 341, 16))
        self.results.setObjectName("results")
        self.errorScheme = QtWidgets.QLabel(self.centralwidget)
        self.errorScheme.setGeometry(QtCore.QRect(810, 90, 351, 16))
        self.errorScheme.setObjectName("errorScheme")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1175, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.buildSolution.setText(_translate("mainWindow", "Решить"))
        self.iterate.setText(_translate("mainWindow", "Проведи итерацию"))
        self.labelMaxIter.setText(_translate("mainWindow", "Введите максимально допустимое число итераций"))
        self.label.setText(_translate("mainWindow", "Задайте точность"))
        self.labelForIt.setText(_translate("mainWindow", "Проведено итераций: 0"))
        self.labelForEpsN.setText(_translate("mainWindow", "Достигнутая точность: 0.0"))
        self.residualEnd.setText(_translate("mainWindow", "Невязка на выходе: 0.0"))
        self.results.setText(_translate("mainWindow", "Результат работы метода Зейделя."))
        self.errorScheme.setText(_translate("mainWindow", "Погрешность схемы: 0.0"))
